spring.application.name=proyecto

spring.datasource.url=jdbc:postgresql://db-aules.uji.es/ei102725dvm
spring.datasource.username=ei102725dvm
spring.datasource.password=ei102725dvm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jdbc.template.show-sql=true